
# This is the Supabase project configuration file
project_id = "ogmqiiyksylbpeixhhmm"

[api]
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[[functions]]
verify_jwt = false
name = "health-check"
schema = "public"

[[functions]]
verify_jwt = true
name = "admin-reset-password"
schema = "public"

[[functions]]
verify_jwt = true
name = "create-checkout"
schema = "public"

[[functions]]
verify_jwt = true
name = "create-partner-checkout"
schema = "public"

[[functions]]
verify_jwt = true
name = "onboard-partner"
schema = "public"

[[functions]]
verify_jwt = true
name = "check-subscription"
schema = "public"

[[functions]]
verify_jwt = false
name = "handle-webhook"
schema = "public"
